# Generated by Django 4.2.5 on 2024-08-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='discounts_active',
            new_name='discount_active',
        ),
    ]
