# Generated by Django 4.2.5 on 2025-05-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shippingmethod_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_city',
            field=models.CharField(default='a', max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_family',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone_number',
            field=models.CharField(default='09123456789', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_postal_code',
            field=models.CharField(default='123456789', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.shippingmethod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=4, default='1.00', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('c', 'Canceled'), ('nd', 'Not Deliver'), ('d', 'Deliver')], default='nd', max_length=2),
        ),
    ]
