# Generated by Django 4.2.5 on 2025-05-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=15),
            preserve_default=False,
        ),
    ]
