# Generated by Django 4.2.5 on 2025-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_number_order_shipping_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('c', 'Canceled'), ('nd', 'Not Delivered'), ('d', 'Delivered')], default='nd', max_length=2),
        ),
    ]
