# Generated by Django 4.2.5 on 2025-06-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_receiver_latitude_order_receiver_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wish_list',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
