# Generated by Django 4.2.5 on 2025-06-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rates_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
