# Generated by Django 4.2.5 on 2025-06-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
