# Generated by Django 4.2.5 on 2025-06-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
