# Generated by Django 4.2.5 on 2025-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_order_total_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='products_total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
