# Generated by Django 4.2.5 on 2025-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_order_order_total_discount_order_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
