# Generated by Django 4.2.5 on 2025-06-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_orderitem_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
